id: 64d247fa61394c57b2e22deea2d7c0a0
title: Toh_514-Discourse_of_Dh%C4%81ra%E1%B9%87%C4%AB_of_Buddha%E2%80%99s_Essence-v2.bo.en
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-008
  eft-text-version: 1.1.10 2021
